
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v20
    - name: Install official clients for tests
      run: |
        nix profile install nixpkgs#litecoin
    - name: Build contract
      run: make all-via-docker
    - name: Run auth_rust tests
      run: cd tests/auth_rust && bash run.sh
